-- 오라클 버전 확인
SELECT * FROM V$VERSION;

-- 사용자 확인
SELECT *
  FROM ALL_USERS
 WHERE 1=1
   AND USERNAME = 'DANNGN'
;
-- 사용자에게 부여된 권한 확인
SELECT * FROM USER_TAB_PRIVS
WHERE 1=1
--  AND GRANTEE = 'DANNGN'
;

-- 데이터베이스 접속 권한 부여
GRANT CREATE SESSION TO DANNGN;
-- 테이블 생성 권한
GRANT CREATE TABLE TO DANNGN;
-- 인덱스 생성 권한
GRANT CREATE ANY INDEX TO DANNGN;
-- 프로시저 생성 권한
GRANT CREATE PROCEDURE TO DANNGN;
-- 함수 생성 권한
GRANT CREATE FUNCTION TO DANNGN;
-- 시퀀스 생성 권한
GRANT CREATE SEQUENCE TO DANNGN;

-- 테이블 스페이스 조회
SELECT *
  FROM DBA_TABLESPACES
 WHERE TABLESPACE_NAME = [테이블스페이스명];

-- 테이블 스페이스 권한 확인
SELECT *
  FROM DBA_TS_QUOTAS
 WHERE TABLESPACE_NAME = [테이블스페이스명]

-- 테이블 스페이스 사용할수 있게 변경
ALTER USER [사용자명] QUOTA UNLIMITED ON [테이블스페이스명];

